# Form implementation generated from reading ui file '.\alert_notification.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys
import pyautogui
from PyQt6.QtCore import Qt
from PyQt6 import QtWidgets
from threading import Thread
from PyQt6.QtCore import QTimer
import alert_notification as alert
from PyQt6.QtWidgets import QApplication, QDialog
from PyQt6.QtCore import Qt, QTimer, QThread, pyqtSignal
from PyQt6 import QtCore, QtGui, QtWidgets

Images_Path = os.path.join(os.getcwd(), "alert.png")

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        screen_width, screen_height = pyautogui.size()
        Form.setGeometry(QtCore.QRect(screen_width-450, 50, 400, 80))
        Form.resize(420, 95)
        # Form.setStyleSheet("background-color: rgb(85, 170, 255);\nborder-radius:10px;")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 400, 80))
        self.frame.setMinimumSize(QtCore.QSize(400, 80))
        self.frame.setMaximumSize(QtCore.QSize(400, 80))
        self.frame.setStyleSheet("background-color: rgb(85, 170, 255);\nborder-radius:10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(60, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(60, 60))
        self.frame_2.setStyleSheet("background-color:transparent")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setStyleSheet("background-color:transparent")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(f"{Images_Path}"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("background-color: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.frame_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Please Login to Account, Otherwise your session will be terminated..."))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = alert.Ui_Form()
    ui.setupUi(Dialog)
    Dialog.setWindowFlags(Qt.WindowType.FramelessWindowHint | Qt.WindowType.Popup)
    Dialog.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
    QTimer.singleShot(5000, Dialog.accept)  # 3000 milliseconds = 3 seconds
    Dialog.show()
    app.exec()
    print("Thread Closed")